[package]
edition = "2021"
name = "sentry-rust-minidump"
version = "0.1.0"

[dependencies]
crash-handler = "0.3.1"
dirs-next = "2"
minidumper = "0.3.1"
sentry = {git = "https://github.com/getsentry/sentry-rust.git"}
uuid = {version = "1", features = ["v4"]}
